# Generated by Django 5.0.6 on 2024-07-07 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=600)),
                (
                    "starting_bid",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ]
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="./images/")),
                ("category", models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
