# Generated by Django 5.0.6 on 2024-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
