# Generated by Django 5.0.6 on 2024-07-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listing_is_open_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="listing",
        ),
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.bid",
            ),
        ),
    ]
