# Generated by Django 5.0.6 on 2024-07-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_bid_listing_alter_listing_current_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="current_bid",
            new_name="bid",
        ),
    ]
