# Generated by Django 5.0.6 on 2024-07-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_rename_current_bid_listing_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bid",
        ),
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.bid",
            ),
        ),
    ]
